2016-06-15 11:19:11.011 -0600	START		Running CalculatorTesting.feature
2016-06-15 11:19:12.012 -0600	Exception		Remote Connection Unavailable	2	on_that_the_calculator_app_is_running_and_in_focus	C://psf/Home/Documents/ePFSuites/gherkin.suite/Scripts/CalculatorTesting.script<SOURCE>
2016-06-15 11:19:12.012 -0600	LogError		that the Calculator app is running and in focus
2016-06-15 11:19:12.012 -0600	Exception		Remote Connection Unavailable	2	on_there_is_no_current_value_in_the_calculator	C://psf/Home/Documents/ePFSuites/gherkin.suite/Scripts/CalculatorTesting.script<SOURCE>
2016-06-15 11:19:12.012 -0600	LogError		there is no current value in the calculator
2016-06-15 11:19:12.012 -0600	Exception		Remote Connection Unavailable	3	on_i_enter_num___num_in_the_calculator	C://psf/Home/Documents/ePFSuites/gherkin.suite/Scripts/CalculatorTesting.script<SOURCE>
2016-06-15 11:19:12.012 -0600	LogError		I enter 2 + 2 in the calculator
2016-06-15 11:19:12.012 -0600	LogWarning		the value returned should be 4
2016-06-15 11:19:12.012 -0600	Exception		Remote Connection Unavailable	2	on_that_the_calculator_app_is_running_and_in_focus	C://psf/Home/Documents/ePFSuites/gherkin.suite/Scripts/CalculatorTesting.script<SOURCE>
2016-06-15 11:19:12.012 -0600	LogError		that the Calculator app is running and in focus
2016-06-15 11:19:12.012 -0600	Exception		Remote Connection Unavailable	2	on_there_is_no_current_value_in_the_calculator	C://psf/Home/Documents/ePFSuites/gherkin.suite/Scripts/CalculatorTesting.script<SOURCE>
2016-06-15 11:19:12.012 -0600	LogError		there is no current value in the calculator
2016-06-15 11:19:12.012 -0600	Exception		Remote Connection Unavailable	3	on_i_enter_num_minus_num_in_the_calculator	C://psf/Home/Documents/ePFSuites/gherkin.suite/Scripts/CalculatorTesting.script<SOURCE>
2016-06-15 11:19:12.012 -0600	LogError		I enter 10 minus 4 in the calculator
2016-06-15 11:19:12.012 -0600	LogWarning		the value returned should be 6
2016-06-15 11:19:12.012 -0600	Exception		Remote Connection Unavailable	2	on_that_the_calculator_app_is_running_and_in_focus	C://psf/Home/Documents/ePFSuites/gherkin.suite/Scripts/CalculatorTesting.script<SOURCE>
2016-06-15 11:19:12.012 -0600	LogError		that the Calculator app is running and in focus
2016-06-15 11:19:12.012 -0600	Exception		Remote Connection Unavailable	2	on_there_is_no_current_value_in_the_calculator	C://psf/Home/Documents/ePFSuites/gherkin.suite/Scripts/CalculatorTesting.script<SOURCE>
2016-06-15 11:19:12.012 -0600	LogError		there is no current value in the calculator
2016-06-15 11:19:12.012 -0600	LogWarning		I multiply <Number1> by <Number2> in the calculator app
2016-06-15 11:19:12.012 -0600	LogSuccess		the app displays the correct answer
2016-06-15 11:19:12.012 -0600	EndTestCase		(Duration:"0.226", Errors:"9", Exceptions:"8", StartTime:"2016-06-15 11:19:11 -0600", Successes:"1", TestCase:"CalculatorTesting.feature", Warnings:"3")
2016-06-15 11:19:12.012 -0600	FAILURE		3 scenarios (3 failed, 0 passed) 12 steps (8 failed, 3 skipped, 1 passed) Execution Time 0:00:01
